# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bjcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjcp.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'planned'), (1, 'primary'), (2, 'secondary'), (3, 'bottled'), (4, 'kegged')], default=1)),
                ('stock', models.PositiveSmallIntegerField(choices=[(0, 'empty'), (1, 'very low'), (2, 'low'), (3, 'high')], default=3)),
                ('description', models.TextField(blank=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.Beer')),
            ],
        ),
    ]
