# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_brewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cellar.Brewery'),
            preserve_default=False,
        ),
    ]
