# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjcp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=255)),
                ('aroma', models.TextField(blank=True, null=True)),
                ('appearance', models.TextField(blank=True, null=True)),
                ('flavor', models.TextField(blank=True, null=True)),
                ('mouthfeel', models.TextField(blank=True, null=True)),
                ('impression', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('comparison', models.TextField(blank=True, null=True)),
                ('examples', models.TextField(blank=True, null=True)),
                ('varieties', models.TextField(blank=True, null=True)),
                ('entry_instructions', models.TextField(blank=True, null=True)),
                ('abv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abv_subcategory', to='bjcp.Stat')),
                ('fg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fg_subcategory', to='bjcp.Stat')),
                ('ibu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ibu_subcategory', to='bjcp.Stat')),
                ('og', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='og_subcategory', to='bjcp.Stat')),
                ('srm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srm_subcategory', to='bjcp.Stat')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tags',
            field=models.ManyToManyField(to='bjcp.Tag'),
        ),
    ]
